"""fix

Revision ID: 1ce370820735
Revises: 3a34d78c3d3c
Create Date: 2016-02-11 13:57:22.436117

"""

# revision identifiers, used by Alembic.
revision = '1ce370820735'
down_revision = '3a34d78c3d3c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
