"""unique

Revision ID: 2cfb0881345e
Revises: 1ce370820735
Create Date: 2016-02-12 22:47:17.463843

"""

# revision identifiers, used by Alembic.
revision = '2cfb0881345e'
down_revision = '1ce370820735'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('calories', sa.FLOAT(), nullable=True))
    op.drop_column('route', 'heat')
    op.create_unique_constraint(None, 'user', ['phone'])
    op.create_unique_constraint(None, 'user_addr', ['uid'])
    op.create_unique_constraint(None, 'user_info', ['uid'])
    op.create_unique_constraint(None, 'user_statistic', ['uid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_statistic', type_='unique')
    op.drop_constraint(None, 'user_info', type_='unique')
    op.drop_constraint(None, 'user_addr', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.add_column('route', sa.Column('heat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('route', 'calories')
    ### end Alembic commands ###
