"""route

Revision ID: 3a34d78c3d3c
Revises: a6ff0d41eb0d
Create Date: 2016-02-11 13:56:18.969394

"""

# revision identifiers, used by Alembic.
revision = '3a34d78c3d3c'
down_revision = 'a6ff0d41eb0d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
