"""seq

Revision ID: 52ee7a7ba87b
Revises: 89389f3c8908
Create Date: 2016-02-13 17:19:15.861914

"""

# revision identifiers, used by Alembic.
revision = '52ee7a7ba87b'
down_revision = '89389f3c8908'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
