"""init22

Revision ID: 554f5c4c6017
Revises: 
Create Date: 2016-02-05 07:23:49.468176

"""

# revision identifiers, used by Alembic.
revision = '554f5c4c6017'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_statistic')
    op.drop_table('route')
    op.drop_table('User_follow')
    op.drop_table('user_info')
    op.drop_table('user_addr')
    op.drop_table('User_timeline')
    op.drop_table('event')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pic', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('tape', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'event_pkey')
    )
    op.create_table('User_timeline',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"User_timeline_id_seq"\'::regclass)'), nullable=False),
    sa.Column('action', sa.CHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'User_timeline_pkey')
    )
    op.create_table('user_addr',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('update_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'user.id'], name=u'user_addr_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'user_addr_pkey')
    )
    op.create_table('user_info',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.CHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'user.id'], name=u'user_info_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'user_info_pkey')
    )
    op.create_table('User_follow',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"User_follow_id_seq"\'::regclass)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'User_follow_pkey')
    )
    op.create_table('route',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avr_speed', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weather', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('heat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cover', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.CHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('create_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'route_pkey')
    )
    op.create_table('user_statistic',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('route', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('star', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('follow', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('follower', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'user.id'], name=u'user_statistic_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'user_statistic_pkey')
    )
    ### end Alembic commands ###
