"""USER

Revision ID: a6ff0d41eb0d
Revises: 21113cce3591
Create Date: 2016-02-11 13:21:39.242034

"""

# revision identifiers, used by Alembic.
revision = 'a6ff0d41eb0d'
down_revision = '21113cce3591'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification', sa.Column('action', sa.CHAR(length=5), nullable=True))
    op.add_column('user_notification', sa.Column('addr', sa.VARCHAR(length=32), nullable=True))
    op.add_column('user_notification', sa.Column('content', sa.VARCHAR(length=150), nullable=True))
    op.add_column('user_notification', sa.Column('create_time', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('user_notification', sa.Column('extra', postgresql.JSON(), nullable=True))
    op.add_column('user_notification', sa.Column('fid', sa.INTEGER(), nullable=True))
    op.add_column('user_notification', sa.Column('operate_time', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('user_notification', sa.Column('state', sa.CHAR(length=2), nullable=True))
    op.add_column('user_timeline', sa.Column('aid', sa.INTEGER(), nullable=True))
    op.drop_column('user_timeline', 'content')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_timeline', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('user_timeline', 'aid')
    op.drop_column('user_notification', 'state')
    op.drop_column('user_notification', 'operate_time')
    op.drop_column('user_notification', 'fid')
    op.drop_column('user_notification', 'extra')
    op.drop_column('user_notification', 'create_time')
    op.drop_column('user_notification', 'content')
    op.drop_column('user_notification', 'addr')
    op.drop_column('user_notification', 'action')
    ### end Alembic commands ###
