"""PostGIS2

Revision ID: 1ef525d651f8
Revises: bac50e0abc42
Create Date: 2016-02-13 21:35:06.070664

"""

# revision identifiers, used by Alembic.
revision = '1ef525d651f8'
down_revision = 'bac50e0abc42'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('uid', sa.INTEGER(), nullable=True))
    op.add_column('user_addr', sa.Column('pos', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_addr', 'pos')
    op.drop_column('route', 'uid')
    ### end Alembic commands ###
