"""rebuild

Revision ID: bac50e0abc42
Revises: 52ee7a7ba87b
Create Date: 2016-02-13 20:22:56.227272

"""

# revision identifiers, used by Alembic.
revision = 'bac50e0abc42'
down_revision = '52ee7a7ba87b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
