"""update

Revision ID: d3578af0e813
Revises: 554f5c4c6017
Create Date: 2016-02-11 02:20:36.928129

"""

# revision identifiers, used by Alembic.
revision = 'd3578af0e813'
down_revision = '554f5c4c6017'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_comment')
    op.drop_table('admin_report')
    op.drop_table('route_like')
    op.drop_table('admin_feedback')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_feedback',
    sa.Column('id', postgresql.INET(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'admin_feedback_pkey')
    )
    op.create_table('route_like',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'route_like_pkey')
    )
    op.create_table('admin_report',
    sa.Column('id', postgresql.INET(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'admin_report_pkey')
    )
    op.create_table('route_comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'route_comment_pkey')
    )
    ### end Alembic commands ###
